services:
  gateway:
    build:
      context: ./app/gateway
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "${FRONTEND_PUBLIC_PORT}:80"
    depends_on:
      - gateway

  auth-service:
    build:
      context: ./app/services/auth-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production

  orders-service:
    build:
      context: ./app/services/orders-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production

  returns-service:
    build:
      context: ./app/services/returns-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production

  warehouse-service:
    build:
      context: ./app/services/warehouse-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production

  users-service:
    build:
      context: ./app/services/users-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production