services:
  gateway:
    build:
      context: ./app/gateway
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/gateway:/app
      - /app/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "${FRONTEND_DEV_PORT}:5173"

  auth-service:
    build:
      context: ./app/services/auth-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/services/auth-service:/app
      - /app/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"

  orders-service:
    build:
      context: ./app/services/orders-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/services/orders-service:/app
      - /app/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"

  returns-service:
    build:
      context: ./app/services/returns-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/services/returns-service:/app
      - /app/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"

  users-service:
    build:
      context: ./app/services/users-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./app/services/users-service:/app
      - /app/node_modules
    command: npm run dev
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"