-- =========================
-- SEED DATA - USERS
-- =========================

INSERT INTO users (nombre, apellido, email, rol)
VALUES
('Juan', 'Perez', 'juan.perez@empresa.com', 'comercial'),
('Ana', 'Gomez', 'ana.gomez@empresa.com', 'comercial'),
('Luis', 'Martinez', 'luis.martinez@empresa.com', 'admin'),
('Carla', 'Lopez', 'carla.lopez@empresa.com', 'comercial'),
('Diego', 'Fernandez', 'diego.fernandez@empresa.com', 'depo');

-- =========================
-- SEED DATA - ORDERS
-- =========================

INSERT INTO orders (
    fecha,
    razon_social,
    ejecutivo_cuenta_id,
    plataforma_venta,
    numero_remito,
    numero_factura,
    tipo_envio_retiro,
    hecho,
    despachado_recibido,
    metodo_envio_retiro,
    nombre_apellido,
    dni_cuit_puerta,
    observaciones_deposito,
    transporte,
    destinatario,
    dni_cuit_encomienda,
    guia_direccion,
    valor_declarado,
    telefono,
    paga_envio,
    observaciones_transporte,
    bultos,
    correo_depo_enviado,
    confirmo_pedido,
    despacho_recibio,
    preparo_pedido,
    pagado,
    external_id
)
VALUES
-- Pedido 1
(
    '2026-03-20',
    'Tech Solutions SA',
    1,
    'Mercado Libre',
    'REM-1001',
    'FAC-2001',
    'PUERTA',
    true,
    false,
    'Moto',
    'Carlos Diaz',
    '20333444556',
    'Frágil',
    'Andreani',
    'Carlos Diaz',
    '20333444556',
    'Av. Siempre Viva 742, Buenos Aires, CABA, 1000',
    150000.00,
    '1133445566',
    true,
    'Entregar en horario laboral',
    2,
    true,
    true,
    false,
    true,
    true,
    'EXT-001'
),

-- Pedido 2
(
    '2026-03-21',
    'Distribuidora Norte SRL',
    2,
    'Tienda Nube',
    'REM-1002',
    'FAC-2002',
    'ENCOMIENDA',
    true,
    true,
    'Correo',
    'Maria Lopez',
    '27222333444',
    '',
    'OCA',
    'Maria Lopez',
    '27222333444',
    'San Martín 123, Córdoba, Córdoba, 5000',
    98000.00,
    '3515558899',
    false,
    '',
    1,
    true,
    true,
    true,
    true,
    true,
    'EXT-002'
),

-- Pedido 3
(
    '2026-03-22',
    'Importadora Sur SA',
    3,
    'Venta Directa',
    'REM-1003',
    'FAC-2003',
    'RETIRO',
    false,
    false,
    'Cliente retira',
    'Jorge Ramirez',
    '20111222333',
    'Esperando confirmación',
    '',
    '',
    '',
    '',
    0,
    '1144556677',
    false,
    '',
    3,
    false,
    false,
    false,
    false,
    false,
    'EXT-003'
),

-- Pedido 4
(
    '2026-03-23',
    'Logistica Express SA',
    4,
    'Mercado Libre',
    'REM-1004',
    'FAC-2004',
    'PUERTA',
    true,
    true,
    'Camión',
    'Pedro Suarez',
    '20399888777',
    '',
    'Andreani',
    'Pedro Suarez',
    '20399888777',
    'Belgrano 456, Rosario, Santa Fe, 2000',
    200000.00,
    '3416667788',
    true,
    'Entrega urgente',
    5,
    true,
    true,
    true,
    true,
    true,
    'EXT-004'
),

-- Pedido 5
(
    '2026-03-24',
    'ElectroShop SRL',
    5,
    'Web Propia',
    'REM-1005',
    'FAC-2005',
    'ENCOMIENDA',
    true,
    false,
    'Correo',
    'Lucia Fernandez',
    '27222999888',
    'Revisar embalaje',
    'Correo Argentino',
    'Lucia Fernandez',
    '27222999888',
    'Mitre 789, Mendoza, Mendoza, 5500',
    175000.00,
    '2615553322',
    true,
    '',
    2,
    true,
    true,
    false,
    true,
    false,
    'EXT-005'
);